overblog_graphql:
    services:
        promise_adapter: 'App\Async\TornadoGqlAdapter'
    definitions:
        auto_mapping: false
        schema:
            quickstart:
                query: Query
                types:
                    - Text
                    - Sentence

        mappings:
            auto_discover: false
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
